### ISSUE TITLE
Stack Overrun on STM32F746ZG Nucleo Board with blinky example

### ISSUE THREAD

**Issue by droofe** [embassy-rs/embassy#2995] opened 2024-05-24 01:00 UTC
Hey there.

I've changed the Cargo.toml and config.toml to reflect the correct chip.

When I `cargo run --release --bin blinky` in `embassy/examples/stm32f7`, it appears that DefaultPreInit returns a stack end address that exceeds the memory map, causing the chip to hard fault after passing `0x2005ffe0.`

```
Status: Halted(Unknown)
Core halted at address 0x0800513e
XPSR: 0x61000003
Currently handling exception 3
Hard Fault!
Return address (LR): 0xfffffff9
-> configurable priority exception has been escalated to hard fault!
	Bus Fault       - BFSR: 0x04
```

**Comment by Dirbaio** [comment] 2024-05-24 13:11
this is probaby due to https://github.com/embassy-rs/stm32-data/issues/301.

try specifying memory.x manually

**Comment by droofe** [comment] 2024-05-24 13:31
Ah interesting. Specifying a custom `memory.x` worked.

**Comment by Dirbaio** [comment] 2024-05-24 13:42
confirmed then. closing in favor of https://github.com/embassy-rs/stm32-data/issues/301.

**Closed** 2024-05-24 13:41 UTC
