### ISSUE TITLE
`embassy-stm32` doesn't build when enabling the `inline-asm` feature in `cortex-m`

### ISSUE THREAD

**Issue by henrikssn** [embassy-rs/embassy#1155] opened 2023-01-16 16:16 UTC
I wonder if there could be some conflict between the build.rs scripts or something?

Here is the rustc command when embassy-stm32 is a dependency (does not build):

```
 Running `rustc --crate-name cortex_m --edition=2018 /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.7.7/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="critical-section"' --cfg 'feature="critical-section-single-core"' --cfg 'feature="inline-asm"' --cfg 'feature="linker-plugin-lto"' -C metadata=6e23b1e13f293cf9 -C extra-filename=-6e23b1e13f293cf9 --out-dir /code/limocotri/cross/target/debug/deps -L dependency=/code/limocotri/cross/target/debug/deps --extern bare_metal=/code/limocotri/cross/target/debug/deps/libbare_metal-67c2a0578e8220d8.rmeta --extern bitfield=/code/limocotri/cross/target/debug/deps/libbitfield-13c4cb6897566af3.rmeta --extern critical_section=/code/limocotri/cross/target/debug/deps/libcritical_section-407a8b1f7e4e8858.rmeta --extern embedded_hal=/code/limocotri/cross/target/debug/deps/libembedded_hal-9249718eeaa30985.rmeta --extern volatile_register=/code/limocotri/cross/target/debug/deps/libvolatile_register-239233c00f9d98d9.rmeta --cap-lints allow --cfg native
```

This is without `embassy-stm32` as dep (builds fine):

```
Running \`rustc --crate-name cortex\_m --edition=2018 /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.7.7/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="critical-section"' --cfg 'feature="critical-section-single-core"' --cfg 'feature="inline-asm"' --cfg 'feature="linker-plugin-lto"' -C metadata=5b0d6aed31a9f448 -C extra-filename=-5b0d6aed31a9f448 --out-dir /code/limocotri/cross/target/thumbv7em-none-eabi/debug/deps --target thumbv7em-none-eabi -L dependency=/code/limocotri/cross/target/thumbv7em-none-eabi/debug/deps -L dependency=/code/limocotri/cross/target/debug/deps --extern bare\_metal=/code/limocotri/cross/target/thumbv7em-none-eabi/debug/deps/libbare\_metal-6a84a3889d0d54de.rmeta --extern bitfield=/code/limocotri/cross/target/thumbv7em-none-eabi/debug/deps/libbitfield-9b0a6591496e465a.rmeta --extern critical\_section=/code/limocotri/cross/target/thumbv7em-none-eabi/debug/deps/libcritical\_section-df0b62c862e2ab8a.rmeta --extern embedded\_hal=/code/limocotri/cross/target/thumbv7em-none-eabi/debug/deps/libembedded\_hal-a9183600a5f1a1bf.rmeta --extern volatile\_register=/code/limocotri/cross/target/thumbv7em-none-eabi/debug/deps/libvolatile\_register-fe50c29243267161.rmeta --cap-lints allow -C link-arg=-Tlink.x -C link-arg=--nmagic -C link-arg=-Tdefmt.x -L /code/limocotri/cross/target/thumbv7em-none-eabi/debug/build/cortex-m-cf52490aca8a52bb/out -l static=cortex-m --cfg cortex\_m --cfg armv7m --cfg armv7em
```

As you see, there are some cfg args missing which makes the cortex-m build fail, but what I don't understand is how embassy-stm32 makes this break

You can reproduce this by adding the `inline-asm` feature to the `cortex-m` dependency of one of the `embassy/examples/stm32f4` and run `cargo build`

**Comment by Dirbaio** [comment] 2023-03-14 16:34
I can't reproduce this anymore on `nightly-2023-02-07`, it was a nightly bug maybe. i'm going to close this, if you still have the problem please open a new issue with updated repro instructions. Thanks!

**Closed by Dirbaio** 2023-03-14 16:34 UTC
